const gUsrJson = 
{
    "ID": "admin",
    "Locale": "zz",
    "ScreenWidth": 0,
    "Page": "pk",
    "Rank": "EMU",
    "Prog": "100%",
    "Fuel": "100",
    "Level": "9999(⊇Svip)",
    "SVip": "SVIP：365天",
    "BVip": "BVIP：365天",
    "Coin1": " - ",
    "Coin2": " - ",
    "Coin3": " - ",
    "Cost": "0",
    "NpcLv": "+33%",
    "AssetRoot": "assets/",
    "ActorDir": "actor/cygames/",
    "ActorExt": ".png",
    "ActorMap": {},
    "EquipDir": "equip/cygames/z",
    "EquipExt": ".png",
    "EquipMap": {}
}
